import React from "react";

export default function Privacy2() {
  return (
    <div>
      <div className="border-b-[2px] border-gray-200 h-20 flex items-center">
        <nav className="max-w-[1100px] w-[90%] mx-auto">
          <h1 className="text-3xl md:text-4xl font-semibold leading-tight">
            Privacy Policy For PixeLift: AI Photo Enhancer
          </h1>
        </nav>
      </div>

      <main className="max-w-[1100px] w-[90%] mx-auto  py-12 text-gray-900">
        {/* Title */}
        <header className="mb-8">
          <h1 className="text-5xl md:text-6xl font-extrabold leading-tight">
            Privacy Policy
          </h1>
          <p className="mt-3 text-xl md:text-2xl text-gray-600">
            Last updated: <span className="font-semibold">July 02, 2025</span>
          </p>
        </header>

        {/* Intro */}
        <section className="mb-8">
          <p className="text-lg leading-relaxed">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className="mt-4 text-lg leading-relaxed">
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy. This Privacy
            Policy has been created with the help of the Privacy Policy
            Generator.
          </p>
        </section>

        {/* Interpretation & Definitions */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Interpretation and Definitions
          </h2>

          <div className="mb-4">
            <h3 className="text-2xl font-semibold">Interpretation</h3>
            <p className="mt-2 leading-relaxed">
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
          </div>

          <div>
            <h3 className="text-2xl font-semibold mb-3">Definitions</h3>

            <ul className="list-disc list-inside space-y-3 text-lg">
              <li>
                <strong>Account</strong> means a unique account created for You
                to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Affiliate</strong> means an entity that controls, is
                controlled by or is under common control with a party, where
                "control" means ownership of 50% or more of the shares, equity
                interest or other securities entitled to vote for election of
                directors or other managing authority.
              </li>
              <li>
                <strong>Application</strong> refers to PixeLift: AI Photo Enhancer, the
                software program provided by the Company.
              </li>
              <li>
                <strong>Company</strong> (referred to as either "the Company",
                "We", "Us" or "Our" in this Agreement) refers to PixeLift: AI Photo Enhancer.
              </li>
              <li>
                <strong>Country</strong> refers to: Pakistan.
              </li>
              <li>
                <strong>Device</strong> means any device that can access the
                Service such as a computer, a cellphone or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Application.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal
                person who processes the data on behalf of the Company. It
                refers to third-party companies or individuals employed by the
                Company to facilitate the Service, to provide the Service on
                behalf of the Company, to perform services related to the
                Service or to assist the Company in analyzing how the Service is
                used.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself (for example, the
                duration of a page visit).
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the
                Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service, as
                applicable.
              </li>
            </ul>
          </div>
        </section>

        {/* Collecting and Using Your Personal Data */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Collecting and Using Your Personal Data
          </h2>

          <div className="mb-6">
            <h3 className="text-2xl font-semibold mb-3">
              Types of Data Collected
            </h3>

            <div className="mb-4">
              <h4 className="text-xl font-semibold">Personal Data</h4>
              <p className="mt-2 leading-relaxed">
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. Personally identifiable information may
                include, but is not limited to:
              </p>
              {/* No explicit bullet items were provided in the source; keep it flexible */}
              <ul className="list-disc list-inside mt-3 space-y-2 text-lg">
                <li>Contact details (e.g. email, phone)</li>
                <li>Account and registration information</li>
                <li>Billing and shipping details</li>
              </ul>
            </div>

            <div>
              <h4 className="text-xl font-semibold">Usage Data</h4>
              <p className="mt-2 leading-relaxed">
                Usage Data is collected automatically when using the Service and
                may include information such as Your Device's IP address,
                browser type and version, the pages of our Service that You
                visit, the time and date of Your visit, the time spent on those
                pages, unique device identifiers and other diagnostic data.
              </p>
              <p className="mt-2 leading-relaxed">
                When You access the Service by or through a mobile device, We
                may collect certain information automatically, including but not
                limited to: mobile device type, device unique ID, mobile OS,
                mobile browser type and other diagnostic data.
              </p>
            </div>
          </div>

          <div>
            <h3 className="text-2xl font-semibold mb-3">
              Use of Your Personal Data
            </h3>

            <ul className="list-disc list-inside space-y-3 text-lg">
              <li>
                To provide and maintain our Service, including to monitor usage.
              </li>
              <li>
                To manage Your Account and registration as a user of the
                Service.
              </li>
              <li>
                For the performance of a contract: development, compliance and
                undertaking of purchase contracts for products, items or
                services.
              </li>
              <li>
                To contact You by email, telephone, SMS, or other electronic
                communication regarding updates, security notices, or
                informational communications.
              </li>
              <li>
                To provide You with news, special offers and general information
                about other goods, services and events we offer (unless You opt
                out).
              </li>
              <li>To manage Your requests and attend to support queries.</li>
              <li>
                For business transfers: to evaluate or conduct mergers,
                divestitures, reorganizations, or similar transfers of assets.
              </li>
              <li>
                For other purposes such as data analysis, identifying usage
                trends and improving our Service, products, marketing and user
                experience.
              </li>
            </ul>
          </div>
        </section>

        {/* Sharing */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Sharing Your Personal Information
          </h2>

          <p className="leading-relaxed mb-4">
            We may share Your personal information in the following situations:
          </p>

          <ul className="list-disc list-inside space-y-3 text-lg">
            <li>
              <strong>With Service Providers:</strong> to monitor and analyze
              the use of our Service and to contact You.
            </li>
            <li>
              <strong>For business transfers:</strong> in connection with
              mergers, financing, asset sales or acquisitions.
            </li>
            <li>
              <strong>With Affiliates:</strong> where affiliates are required to
              honor this Privacy Policy.
            </li>
            <li>
              <strong>With business partners:</strong> to offer You certain
              products, services or promotions.
            </li>
            <li>
              <strong>With other users:</strong> when You share information or
              interact publicly, such information may be visible to others.
            </li>
            <li>
              <strong>With Your consent:</strong> for any other purpose with
              Your agreement.
            </li>
          </ul>
        </section>

        {/* Retention */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Retention of Your Personal Data
          </h2>
          <p className="leading-relaxed">
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use Your Personal Data to the extent necessary to comply
            with our legal obligations, resolve disputes, and enforce our legal
            agreements and policies.
          </p>
          <p className="mt-3 leading-relaxed">
            Usage Data is generally retained for a shorter period of time unless
            used to strengthen security, improve functionality, or when legally
            required to retain it longer.
          </p>
        </section>

        {/* Transfer */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Transfer of Your Personal Data
          </h2>
          <p className="leading-relaxed">
            Your information may be processed at the Company's operating offices
            and in any other places where the parties involved in processing are
            located — this may involve transfer to locations with different data
            protection laws. Your submission of information constitutes
            agreement to that transfer.
          </p>
          <p className="mt-3 leading-relaxed">
            The Company will take reasonable steps to ensure data is treated
            securely and that transfers only occur when adequate controls are in
            place.
          </p>
        </section>

        {/* Delete */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            User Content and Media Processing
          </h2>
          <p className="leading-relaxed">
            We do not collect or analyze biometric face data. When you upload an
            image, it is temporarily stored on our server for the sole purpose
            of enhancing a photo. Images are not shared with third parties and
            are automatically deleted after processing.
          </p>
        </section>

        {/* Disclosure */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Disclosure of Your Personal Data
          </h2>

          <ul className="list-disc list-inside space-y-3 text-lg">
            <li>
              <strong>Business Transactions:</strong> If the Company is involved
              in a merger, acquisition or asset sale, Your Personal Data may be
              transferred. Notice will be provided before transfer.
            </li>
            <li>
              <strong>Law enforcement:</strong> The Company may be required to
              disclose Your Personal Data in response to valid requests by
              public authorities (e.g., a court or government agency).
            </li>
            <li>
              <strong>Other legal requirements:</strong> We may disclose
              Personal Data to comply with legal obligations or to protect
              rights, safety, or the public.
            </li>
          </ul>
        </section>

        {/* Security */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Security of Your Personal Data
          </h2>
          <p className="leading-relaxed">
            The security of Your Personal Data is important to Us. While we use
            commercially acceptable means to protect Your data, no method of
            transmission or storage is 100% secure and we cannot guarantee
            absolute security.
          </p>
        </section>

        {/* Children's Privacy */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Children's Privacy
          </h2>
          <p className="leading-relaxed">
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under 13. If You believe a child has provided us Personal Data,
            please contact Us and we will take steps to remove that information.
          </p>
        </section>

        {/* Links */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Links to Other Websites
          </h2>
          <p className="leading-relaxed">
            Our Service may contain links to third-party sites. We are not
            responsible for their content, privacy policies, or practices. We
            strongly recommend reviewing the privacy policy of every site you
            visit.
          </p>
        </section>

        {/* Changes */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Changes to this Privacy Policy
          </h2>
          <p className="leading-relaxed">
            We may update this Privacy Policy from time to time. We will notify
            You of changes by posting the new Privacy Policy on this page and,
            if appropriate, via email or a prominent notice on Our Service.
          </p>
        </section>

        {/* Contact */}
        <section className="mb-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Contact Us</h2>
          <p className="leading-relaxed">
            If you have any questions about this Privacy Policy, You can contact
            us:
          </p>

          <ul className="list-disc list-inside mt-4 space-y-2 text-lg">
            <li>
              By email:{" "}
              <a className="text-blue-600" href="mailto:akash@devsrank.com">
                akash@devsrank.com
              </a>
            </li>
            <li>
              By visiting:{" "}
              <a
                className="text-blue-600"
                href="https://devsrank.com/"
                target="_blank"
                rel="noreferrer"
              >
                devsrank.com
              </a>
            </li>
            <li>
              By phone:{" "}
              <a className="text-blue-600" href="tel:+923001234968">
                +92 300 1234968
              </a>
            </li>
          </ul>

          <p className="mt-4 text-sm text-gray-500">
            Generated using TermsFeed Privacy Policy Generator
          </p>
        </section>
      </main>
    </div>
  );
}
